import os
from dotenv import load_dotenv

load_dotenv()

CRICFY_FIREBASE_API_KEY = os.getenv("CRICFY_FIREBASE_API_KEY", "")
CRICFY_FIREBASE_APP_ID = os.getenv("CRICFY_FIREBASE_APP_ID", "")
CRICFY_FIREBASE_PROJECT_NUMBER = os.getenv("CRICFY_FIREBASE_PROJECT_NUMBER", "")

CRICIFY_PROVIDER_SECRET1 = os.getenv("CRICIFY_PROVIDER_SECRET1", "")
CRICIFY_PROVIDER_SECRET2 = os.getenv("CRICIFY_PROVIDER_SECRET2", "")
